game_name: "Acrobot-v1"
max_episode_steps: 500

env_wrappers: []

alg_args:
  dqn:
    lr: 0.0005
    epsilon_anneal_time: 20000
    sample_step_num: 64
    max_buffer_steps: 5000
    learning_starts: 1000
    target_update_interval: 200
    t_max: 300600
  reinforce:
    sample_episode_num: 8
    max_buffer_episodes: 8
    lr: 0.0005
    critic_lr: 0.001
    hidden_size: 128
    t_max: 300600
