game_name: "CliffWalking-v0"
max_episode_steps: 100

env_wrappers: []

alg_args:
  dqn:
    wrapper: ["state_to_one_hot"]
    lr: 0.001
    epsilon_anneal_time: 20000
    sample_step_num: 64
    max_buffer_steps: 5000
    learning_starts: 500
    target_update_interval: 200
    hidden_size: 64
    t_max: 80000
  reinforce:
    wrapper: ["state_to_one_hot"]
    gamma: 1.0
    sample_episode_num: 8
    max_buffer_episodes: 8
    lr: 0.0005
    critic_lr: 0.001
    hidden_size: 128
    value_train_iters: 20
    t_max: 100000
  q_learning:
    gamma: 1.0
    lr: 0.5
    epsilon_finish: 0.01
    epsilon_anneal_time: 20000
    t_max: 30000
  sarsa:
    gamma: 1.0
    lr: 0.5
    epsilon_finish: 0.01
    epsilon_anneal_time: 20000
    t_max: 30000
