game_name: "FrozenLake8x8-v1"
max_episode_steps: 200

t_max: 200000

env_wrappers: []

alg_args:
  dqn:
    wrapper: ["state_to_one_hot"]
    lr: 0.0005
    epsilon_anneal_time: 80000
    sample_step_num: 64
    max_buffer_steps: 10000
    learning_starts: 1000
    target_update_interval: 200
    hidden_size: 128
  reinforce:
    wrapper: ["state_to_one_hot"]
    sample_episode_num: 32
    max_buffer_episodes: 32
    lr: 0.001
    critic_lr: 0.001
    hidden_size: 128
    t_max: 200000
