game_name: "LunarLander-v3"
max_episode_steps: 1000

t_max: 400000

env_wrappers: []

alg_args:
  dqn:
    lr: 0.0005
    epsilon_anneal_time: 50000
    buffer_size: 20000
    learning_starts: 2000
    target_update_interval: 200
  reinforce:
    batch_size: 8
    lr: 0.0005
    critic_lr: 0.001
    hidden_size: 128
    t_max: 400000
