game_name: "Taxi-v3"
max_episode_steps: 200

env_wrappers: []

alg_args:
  dqn:
    wrapper: ["state_to_one_hot"]
    gamma: 1.0
    lr: 0.0003
    epsilon_finish: 0.05
    epsilon_anneal_time: 120000
    sample_step_num: 128
    max_buffer_steps: 50000
    learning_starts: 5000
    target_update_interval: 500
    hidden_size: 128
    t_max: 150300
  reinforce:
    wrapper: ["state_to_one_hot"]
    sample_episode_num: 16
    max_buffer_episodes: 16
    lr: 0.001
    critic_lr: 0.001
    hidden_size: 128
    t_max: 200000
  q_learning:
    gamma: 1.0
    lr: 0.3
    epsilon_finish: 0.05
    epsilon_anneal_time: 100000
    t_max: 100300
  sarsa:
    gamma: 0.99
    lr: 0.2
    epsilon_finish: 0.05
    epsilon_anneal_time: 200000
    t_max: 500300
