actor_critic:
  runner: "serial"
  controller: "basic_controller"
  buffer: "basic_buffer"
  learner: "actor_critic"
  max_buffer_episodes: 4
  sample_episode_num: 4

  agent: "simple_actor"
  critic: "simple_critic"
  action_selector: "policy_distribution"
  hidden_size: 256

  gamma: 0.99
  actor_lr: 0.001
  critic_lr: 0.001

dqn:
  runner: "serial"
  t_max: 200000

  controller: "basic_controller"
  buffer: "basic_buffer"
  learner: "dqn"

  lr: 0.001
  gamma: 0.99
  target_update_interval: 100

  agent: "simple_critic"
  hidden_size: 128
  action_selector: "epsilon_greedy"
  epsilon_start: 1.0
  epsilon_finish: 0.01
  epsilon_anneal_time: 4000

  sample_step_num: 64
  max_buffer_steps: 10000
  learning_starts: 500
  learn_every_steps: 1

q_learning:
  runner: "serial"
  controller: "basic_controller"
  buffer: "basic_buffer"
  learner: "q_learning"

  t_max: 200000
  batch_update: false
  max_buffer_steps: 1
  q_init_val: 0.0
  agent: "q_table"
  gamma: 0.99
  action_selector: "epsilon_greedy"
  epsilon_start: 1.0
  epsilon_finish: 0.05
  epsilon_anneal_time: 50000

reinforce:
  runner: "serial"
  controller: "basic_controller"
  buffer: "basic_buffer"
  learner: "reinforce"

  sample_episode_num: 2
  max_buffer_episodes: 2
  t_max: 240000

  agent: "simple_actor"

  baseline: true
  critic_lr: 0.01
  value_train_iters: 10
  critic:
    name: "full_connect_value"
    hidden_dim: 16
    n_layers: 3

  hidden_size: 64
  action_selector: "policy_distribution"

  formula: 3

sarsa:
  runner: "serial"
  controller: "basic_controller"
  buffer: "basic_buffer"
  learner: "sarsa"

  t_max: 200000
  batch_update: false
  max_buffer_steps: 1
  q_init_val: 0.0
  agent: "q_table"
  gamma: 0.99
  action_selector: "epsilon_greedy"
  epsilon_start: 1.0
  epsilon_finish: 0.05
  epsilon_anneal_time: 50000
