# --- Logging options ---
use_tensorboard: True
local_results_path: "results"
log_interval: 2000

# --- RL hyperparameters ---
gamma: 0.99
lr: 0.001
sample_step_num: 1
sample_episode_num: 1

# Historical decision-making process
builder: "basic_builder"
history_frame_num: 0
history_action_num: 0

# Test arguments
test_nepisode: 32
eval_nepisode: 10
test_interval: 5000
render: False
render_mode: "human"

# Model load and save
save_model: False
save_model_interval: 0
checkpoint_path: ""
load_step: 0
evaluate: False

# device control
device: "cuda"
# dtype control
dtype: "float32"

name: "rl_learn"

default_wrappers: ["all_to_tensor",]
env_wrappers: []
alg_env_wrappers: []

env: "gym"
game_name: "CartPole-v1"
max_episode_steps: 500
make_kwargs: {}
