# --- Logging options ---
use_tensorboard: True
local_results_path: "results"
log_interval: 5000

# --- RL hyperparameters ---
gamma: 0.99
lr: 0.001
batch_size: 4
buffer_size: 4

# Historical decision-making process
builder: "basic_builder"
history_frame_num: 0
history_action_num: 0

# Test arguments
test_nepisode: 32
test_interval: 5000

# Model load and save
save_model: False
save_model_interval: 0

# device control
device: "cuda"
# dtype control
dtype: "float32"

name: "rl_learn"

default_wrappers: ["all_to_tensor",]
