runner: "episode"
controller: "basic_controller"
buffer: "basic_buffer"
learner: "actor_critic"

agent: "simple_actor"
critic: "simple_critic"
action_selector: "policy_distribution"
hidden_size: 256

gamma: 0.99
actor_lr: 0.001
critic_lr: 0.001