runner: "episode"

controller: "basic_controller"
buffer: "basic_buffer"
learner: "dqn"

lr: 0.001
target_update_interval: 10

agent: "simple_critic"
hidden_size: 64
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.01
epsilon_anneal_time: 50000

batch_size: 32
buffer_size: 32