runner: "episode"

controller: "basic_controller"
buffer: "basic_buffer"
learner: "dqn"

target_update_interval: 32

agent: "simple_critic"
hidden_size: 256
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 5000