# --- DQN specific parameters ---

# --- args for DQN controllers
controller: "value"
critic: "simple_critic"
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "default"


# use XXX to train
agent_out_put_type: "value"