# --- DQN specific parameters ---

# --- args for DQN controllers
controller: "basic_controller"
buffer: "basic_buffer"
buffer_size: "64"
learner: "dqn"

critic: "simple_critic"
hidden_size: 256
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"


# use XXX to train
agent_out_put_type: "value"