# --- General config  ---
runner: "default"

# 超参数
gamma: 0.99  # 折扣因子
gae_lambda: 0.95  # GAE参数
clip_epsilon: 0.2  # 裁剪参数
epochs: 10  # 每次收集数据后进行多少次训练迭代
batch_size: 32  # 批次大小
value_loss_weight: 0.5  # 价值函数损失的权重
entropy_loss_weight: 0.01  # 熵损失的权重

# use XXX to train
agent_out_put_type: "distribution"