runner: "episode"

controller: "basic_controller"
buffer: "basic_buffer"
learner: "ppo"

# 超参数
gamma: 0.99  # 折扣因子
lmbda: 0.95  # GAE的参数
clip_epsilon: 0.2  # 裁剪参数
epochs: 10  # 每次收集数据后进行多少次训练迭代
batch_size: 4  # 批次大小
critic_loss_weight: 0.5  # 价值函数损失的权重
entropy_loss_weight: 0.01  # 熵损失的权重
actor_lr: !!float 1e-3  # 演员的学习率
critic_lr: !!float 1e-2  # 评论员的学习率

agent: "simple_critic"
hidden_size: 256
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 5000