runner: "episode"
controller: "basic_controller"
buffer: "basic_buffer"
learner: "reinforce"

batch_size: 16
buffer_size: 16

agent: "simple_actor"
hidden_size: 64
action_selector: "policy_distribution"

baseline: true

formula: 3